# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7665c4437ae55abc4fbb61fbb518551c"
name = "SmartTag AI"
application_url = "https://smart-tag-ai.monching-desierto.space"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[access]
embedded_app_direct_api_access = true

[auth]
redirect_urls = [ "https://smart-tag-ai.monching-desierto.space/auth/callback" ]
