# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7665c4437ae55abc4fbb61fbb518551c"
name = "SmartTag AI"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  topics = [ "products/create" ]

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
